import { Inter } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "@/Providers";
// import { getServerSession } from "next-auth";
// import { authOptions } from "./api/auth/[...nextauth]/route";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/ui/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const session = await getServerSession(authOptions);
  // console.log("RootLayout session:", session?.user);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <ToastContainer />
          <AuthProvider>
            {" "}
            <Header />
            {children}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
/*
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/Providers";
// import { getServerSession } from "next-auth";
// import { authOptions } from "./api/auth/[...nextauth]/route";
// import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project Management",
  description: "Project Management Dashboard",
};

export default async function RootLayout({ children }) {
  // const session = await getServerSession(authOptions);
  // if (!session?.user) redirect("/sign-in");
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ToastContainer />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
*/
